version: '3.8'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: buffalo_app
#    command: /bin/app
#    working_dir: /src/sharaphka
#    volumes:
#      - .:/src/sharaphka
#    ports:
#      - "3000:3000"
#    environment:
#      - DATABASE_URL=postgres://postgres:password@db:5432/sharaphka?sslmode=disable
#      - ADDR=0.0.0.0
#    networks:
#      app_net:
#        ipv4_address: 192.168.80.2
#    depends_on:
#      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sharaphka
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 192.168.80.3

networks:
  app_net:
    ipam:
      config:
        - subnet: 192.168.80.0/20

volumes:
  postgres_data:
